# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - sudo apt-get install -y upx
builds:
  - id: ehco
    main: ./cmd/ehco/main.go
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goarch:
      - amd64
      - arm64
      - darwin/arm64
    goarm:
      - 7
    goos:
      - linux
      - darwin
      - windows
    hooks:
      post: ls dist/ && upx dist/*
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
